name: Project build & Test

on:
    push:
        branches: ["main", "develop"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java version
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "microsoft"

            - name: Build with Maven
              run: mvn clean install

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: java-app
                  path: "${{ github.workspace }}/target/*.jar"

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java version
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "microsoft"
            - name: Run tests
              run: mvn test
            - name: Generate test report
              run: mvn jacoco:report
            - name: Upload test report
              uses: actions/upload-artifact@v4
              with:
                  name: test-reports
                  path: "${{ github.workspace }}/target/site/jacoco/"
                  retention-days: 5
            - name: final verify
              run: mvn clean verify